USE app_storage;
DROP TABLE IF EXISTS category_subcategory;
DROP TABLE IF EXISTS subcategory_businesses;
DROP TABLE IF EXISTS category_table;
DROP TABLE IF EXISTS subcategory_table;
DROP TABLE IF EXISTS businesses_table;

CREATE TABLE `category_table`(
`id` int(11) NOT NULL AUTO_INCREMENT,
`name` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY (`name`)
) ENGINE=InnoDB;

CREATE TABLE `subcategory_table`(
`id` int(11) NOT NULL AUTO_INCREMENT,
`name` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY (`name`)
) ENGINE=InnoDB;

CREATE TABLE `category_subcategory`(
`catId` int(11) NOT NULL,
`subcatId` int(11) NOT NULL,
PRIMARY KEY (`catId`, `subcatId`),
FOREIGN KEY (`catId`) REFERENCES `category_table`(`id`) ON DELETE CASCADE,
FOREIGN KEY (`subcatId`) REFERENCES `subcategory_table`(`id`) ON DELETE CASCADE,
UNIQUE KEY (`catId`, `subcatId`)
) ENGINE=InnoDB;

CREATE TABLE `businesses_table`(
`id` int(11) NOT NULL AUTO_INCREMENT,
`name` varchar(255) NOT NULL,
`phoneNumber` varchar(20),
`streetAddress` varchar(255),
`city` varchar(255),
`state` varchar(255),
`zipCode` varchar(255),
`hours` varchar(255),
`webpage` varchar(255),
PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE `subcategory_businesses`(
`subcatId` int(11) NOT NULL,
`businessId` int(11) NOT NULL,
PRIMARY KEY (`subcatId`, `businessId`),
FOREIGN KEY (`subcatId`) REFERENCES `subcategory_table`(`id`) ON DELETE CASCADE,
FOREIGN KEY (`businessId`) REFERENCES `businesses_table`(`id`) ON DELETE CASCADE,
UNIQUE KEY (`subcatId`, `businessId`)
) ENGINE=InnoDB;

INSERT INTO category_table (name) values
("Household"), 
("Bedding/bath"), 
("Children's goods"), 
("Appliances-small"), 
("Appliances-large"),
("Building/home improvement"), 
("Wearable items"), 
("Useable electronics"), 
("Sporting equipment/camping"),
("Garden"), 
("Food"), 
("Medical supplies"), 
("Office equipment"), 
("Packing materials"), 
("Miscellaneous"),
("Repair items");

INSERT INTO subcategory_table (name)
values
("Arts and crafts"),
("Barbeque grills"),
("Books"),
("Canning jars"),
("Cleaning supplies"),
("Clothes hangers"),
("Cookware"),
("Dishes"),
("Fabric"),
("Food storage containers"),
("Furniture"),
("Luggage"),
("Mattresses"),
("Ornaments"),
("Toiletries"),
("Utensils"),
("Blankets"),
("Comforters"),
("Linens"),
("Sheets"),
("Small rugs"),
("Towels"),
("Baby carriers"),
("Baby gates"),
("Bike trailers"),
("Child car seats"),
("Clothes"),
("Crayons"),
("Cribs"),
("Diapers"),
("High chairs"),
("Maternity"),
("Musical instruments"),
("Nursing items"),
("Playpens"),
("School supplies"),
("Strollers"),
("Toys"),
("Blenders"),
("Dehumidifiers"),
("Fans"),
("Microwaves"),
("Space heaters"),
("Toasters"),
("Vacuum cleaners"),
("Dishwashers"),
("Freezers"),
("Refrigerators"),
("Stoves"),
("Washers/dryers"),
("Bricks"),
("Carpet padding"),
("Carpets"),
("Ceramic tiles"),
("Doors"),
("Drywall"),
("Electrical supplies"),
("Hand tools"),
("Hardware"),
("Insulation"),
("Ladders"),
("Light fixtures"),
("Lighting ballasts"),
("Lumber"),
("Motors"),
("Paint"),
("Pipe"),
("Plumbing"),
("Power tools"),
("Reusable metal items"),
("Roofing"),
("Vinyl"),
("Windows"),
("Belts"),
("Boots"),
("Coats"),
("Hats"),
("Rainwear"),
("Sandals"),
("Shoes"),
("Calculators"),
("Cameras"),
("Cassette players"),
("Cd players"),
("Cds"),
("Cell phones"),
("Computers"),
("Curling irons"),
("DVD players"),
("Game consoles"),
("GPS systems"),
("Hair dryers"),
("Monitors"),
("MP3 players"),
("Printers"),
("Projectors"),
("Receivers"),
("Scanners"),
("Speakers"),
("Tablets"),
("Telephones"),
("TVs"),
("Backpacks"),
("Balls"),
("Barbells"),
("Bicycles"),
("Bike tires"),
("Camping equipment"),
("Daypacks"),
("Dumbbells"),
("Exercise equipment"),
("Golf clubs"),
("Helmets"),
("Hiking boots"),
("Skateboards"),
("Skis"),
("Small boats"),
("Snowshoes"),
("Sporting goods"),
("Tennis rackets"),
("Tents"),
("Chain saws"),
("Fencing"),
("Garden pots"),
("Garden tools"),
("Hand clippers"),
("Hoses"),
("Lawn furniture"),
("Livestock supplies"),
("Loppers"),
("Mowers"),
("Seeders"),
("Soil amendment"),
("Sprinklers"),
("Wheel barrows"),
("Beverages"),
("Surplus garden produce"),
("Unopened canned goods"),
("Unopened packaged food"),
("Adult diapers"),
("Blood pressure monitors"),
("Canes"),
("Crutches"),
("Eye glasses"),
("Glucose meters"),
("Hearing aids"),
("Hospital beds"),
("Reach extenders"),
("Shower chairs"),
("Walkers"),
("Wheelchairs"),
("Fax machines"),
("Headsets"),
("Office furniture"),
("Paper shredders"),
("Printer cartridge refilling"),
("Bubble wrap"),
("Clean foam peanuts"),
("Foam sheets"),
("Egg cartons"),
("Firewood"),
("Paper bags"),
("Pet supplies"),
("Shopping bags"),
("Vehicles/parts"),
("Computer paper"),
("Small appliances"),
("Lamps"),
("Lawn power equipment"),
("Outdoor gear"),
("Shoes, boots"),
("Upholstery, car"),
("Upholstery, furniture")
;

INSERT INTO category_subcategory(catId, subcatId)
values
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Arts and crafts")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Barbeque grills")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Books")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Canning jars")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Cleaning supplies")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Clothes hangers")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Cookware")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Dishes")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Fabric")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Food storage containers")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Furniture")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Luggage")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Mattresses")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Ornaments")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Toiletries")),
((SELECT id FROM category_table WHERE name = "Household"), (SELECT id FROM subcategory_table WHERE name = "Utensils"));

INSERT INTO category_subcategory(catId, subcatId)
values
((SELECT id FROM category_table WHERE name = "Bedding/bath"), (SELECT id FROM subcategory_table WHERE name = "Blankets")),
((SELECT id FROM category_table WHERE name = "Bedding/bath"), (SELECT id FROM subcategory_table WHERE name = "Comforters")),
((SELECT id FROM category_table WHERE name = "Bedding/bath"), (SELECT id FROM subcategory_table WHERE name = "Linens")),
((SELECT id FROM category_table WHERE name = "Bedding/bath"), (SELECT id FROM subcategory_table WHERE name = "Sheets")),
((SELECT id FROM category_table WHERE name = "Bedding/bath"), (SELECT id FROM subcategory_table WHERE name = "Small rugs")),
((SELECT id FROM category_table WHERE name = "Bedding/bath"), (SELECT id FROM subcategory_table WHERE name = "Towels"));

INSERT INTO category_subcategory(catId, subcatId)
values
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Arts and crafts")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Baby carriers")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Baby gates")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Bike trailers")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Books")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Child car seats")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Clothes")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Crayons")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Cribs")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Diapers")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "High chairs")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Maternity")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Musical instruments")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Nursing items")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Playpens")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "School supplies")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Strollers")),
((SELECT id FROM category_table WHERE name = "Children's goods"), (SELECT id FROM subcategory_table WHERE name = "Toys"));


INSERT INTO category_subcategory(catId, subcatId)
values
((SELECT id FROM category_table WHERE name = "Appliances-small"), (SELECT id FROM subcategory_table WHERE name = "Blenders")),
((SELECT id FROM category_table WHERE name = "Appliances-small"), (SELECT id FROM subcategory_table WHERE name = "Dehumidifiers")),
((SELECT id FROM category_table WHERE name = "Appliances-small"), (SELECT id FROM subcategory_table WHERE name = "Fans")),
((SELECT id FROM category_table WHERE name = "Appliances-small"), (SELECT id FROM subcategory_table WHERE name = "Microwaves")),
((SELECT id FROM category_table WHERE name = "Appliances-small"), (SELECT id FROM subcategory_table WHERE name = "Space heaters")),
((SELECT id FROM category_table WHERE name = "Appliances-small"), (SELECT id FROM subcategory_table WHERE name = "Toasters")),
((SELECT id FROM category_table WHERE name = "Appliances-small"), (SELECT id FROM subcategory_table WHERE name = "Vacuum cleaners"));

INSERT INTO businesses_table (name, phoneNumber, streetAddress, city, state, zipCode, hours, webpage)
values
("Book Binding","(541) 757-9861", "108 SW 3rd St", "Corvallis", "OR", "97333", "", "http://www.cornerstoneassociates.com/bj-bookbinding-about-us.html"), 
("Cell Phone Sick Bay","(541) 230-1785", "252 SW Madison Ave, Suite 110", "Corvallis", "OR", "97333", "", ""), 
("Geeks 'N' Nerds","(541) 753-0018", "950 Southeast Geary St Unit D", "Albany", "OR", "97321", "", "http://www.computergeeksnnerds.com/"), 
("Specialty Sewing By Leslie","(541) 758-4556", "225 SW Madison Ave", "Corvallis", "OR", "97333", "", "http://www.specialtysewing.com/Leslie_Seamstress/Welcome.html"), 
("Corvallis Technical","(541) 704-7009", "966 NW Circle Blvd", "Corvallis", "OR", "", "", "http://www.corvallistechnical.com/"), 
("Bellevue Computers","541-757-3487", "1865 NW 9th St", "Corvallis", "OR", "", "", "http://www.bellevuepc.com/"), 
("OSU Repair Fair","541-737-5398", "Oregon State University Property Services Building 644 S.W. 13th St ", "Corvallis", "OR", "", "", "http://fa.oregonstate.edu/surplus"),
("P.K Furniture Repair & Refinishing","541-230-1727", "5270 NW Hwy 99", "Corvallis", "OR", "97333", "", "http://www.pkfurniturerefinishing.net/"),  
("Furniture Restoration Center","(541) 929-6681", "1321 Main St", "Philomath", "OR", "", "", "http://restorationsupplies.com/"), 
("Power equipment","(541) 757-8075", "713 NE Circle Blvd", "Corvallis", "OR", "97330", "", "https://corvallispowerequipment.stihldealer.net/"), 
("Robnett's","(541) 753-5531", "400 SW 2nd St", "Corvallis", "OR", "97333", "", "http://ww3.truevalue.com/robnetts/Home.aspx"),
("Footwise","(541) 757-0875", "301 SW Madison Ave #100", "Corvallis", "OR", "97333", "", "http://www.sedlaksshoes.net/"),
("Sedlack","(541) 752-1498", "225 SW 2nd St", "Corvallis", "OR", "97333", "", "http://footwise.com/"),
("Foam Man","(541) 754-9378", "2511 NW 9th St", "Corvallis", "OR", "97330", "", "http://www.thefoammancorvallis.com/"),
("Albany-Corvallis ReUseIt ","", "", "", "", "", "", "free items:  groups.yahoo.com"),
("Arc Thrift Stores","", "NW Beca", "Corvallis", "OR", "", "", ""),
("Arc Thrift Stores","", "Main St", "Philomath", "OR", "", "", ""),
("Beekman Place Antique Mall","541-753-8250", "601 SW Western Blvd", "", "OR", "", "", ""),
("Benton County Extension / 4-H  Activities","541-766-6750", "1849 NW 9th", "", "OR", "", "", ""),
("Benton County Master Gardeners","541-766-6750", "1849 NW 9th St", "", "OR", "", "", ""),
("Book Bin","", "4th St", "", "OR", "", "", ""),
("Browser's Bookstore","", "4th St", "", "OR", "", "", ""),
("Boys & Girls Club / STARS (after school programs)","541-757-1909", "", "", "OR", "", "", ""),
("Buckingham Palace","541-752-7980", "600 SW 3rd St", "", "OR", "", "Fri-Sun only", ""),
("CARDV (Center Against Rape/Domestic Violence)","541-758-0219", "", "", "OR", "", "", ""),
("Career Closet for Women","541-754-6979", "942 NW 9th, Ste.A", "", "OR", "", "", ""),
("Cat's Meow Humane Society Thrift Shop","541-757-0573", "411 SW 3rd St", "", "OR", "", "", ""),
("Children's Farm Home","541-757-1852", "Hway 20 btw Corvallis & Albany", "", "OR", "", "", ""),
("Chintimini Wildlife Rehabilitation Ctr","541-745-5324", "311 Lewisburg Rd", "", "OR", "", "", ""),
("Community Outreach (homeless shelter)","541-758-3000", "865 NW Reiman", "", "OR", "", "", ""),
("Corvallis Environmental Center","541-753-9211", "214 SW Monroe Ave", "", "OR", "", "", ""),
("Corvallis Bicycle Collective","541-224-6885", "33900 SE Roche Ln/Hwy 34", "", "OR", "", "", ""),
("CorvallisFurniture.com","541-231-8103", "720 NE Granger Ave, Bldg J", "", "OR", "", "", "");

